/*
 * This file is generated by jOOQ.
*/
package my.jooq.entities.autogen;


import javax.annotation.Generated;

import my.jooq.entities.autogen.tables.Address;
import my.jooq.entities.autogen.tables.FlywaySchemaHistory;
import my.jooq.entities.autogen.tables.Person;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>jooqdb</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADDRESS_PERSON_ID = Indexes0.ADDRESS_PERSON_ID;
    public static final Index ADDRESS_PRIMARY = Indexes0.ADDRESS_PRIMARY;
    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index FLYWAY_SCHEMA_HISTORY_PRIMARY = Indexes0.FLYWAY_SCHEMA_HISTORY_PRIMARY;
    public static final Index PERSON_PRIMARY = Indexes0.PERSON_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ADDRESS_PERSON_ID = createIndex("person_id", Address.ADDRESS, new OrderField[] { Address.ADDRESS.PERSON_ID }, false);
        public static Index ADDRESS_PRIMARY = createIndex("PRIMARY", Address.ADDRESS, new OrderField[] { Address.ADDRESS.ID }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index FLYWAY_SCHEMA_HISTORY_PRIMARY = createIndex("PRIMARY", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index PERSON_PRIMARY = createIndex("PRIMARY", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
    }
}
