/*
 * This file is generated by jOOQ.
*/
package my.jooq.entities.autogen;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import my.jooq.entities.autogen.tables.Address;
import my.jooq.entities.autogen.tables.FlywaySchemaHistory;
import my.jooq.entities.autogen.tables.Person;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooqdb extends SchemaImpl {

    private static final long serialVersionUID = -1608612259;

    /**
     * The reference instance of <code>jooqdb</code>
     */
    public static final Jooqdb JOOQDB = new Jooqdb();

    /**
     * The table <code>jooqdb.address</code>.
     */
    public final Address ADDRESS = my.jooq.entities.autogen.tables.Address.ADDRESS;

    /**
     * The table <code>jooqdb.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = my.jooq.entities.autogen.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jooqdb.person</code>.
     */
    public final Person PERSON = my.jooq.entities.autogen.tables.Person.PERSON;

    /**
     * No further instances allowed
     */
    private Jooqdb() {
        super("jooqdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Person.PERSON);
    }
}
