/*
 * This file is generated by jOOQ.
*/
package my.jooq.entities.autogen;


import javax.annotation.Generated;

import my.jooq.entities.autogen.tables.Address;
import my.jooq.entities.autogen.tables.FlywaySchemaHistory;
import my.jooq.entities.autogen.tables.Person;


/**
 * Convenience access to all tables in jooqdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqdb.address</code>.
     */
    public static final Address ADDRESS = my.jooq.entities.autogen.tables.Address.ADDRESS;

    /**
     * The table <code>jooqdb.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = my.jooq.entities.autogen.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jooqdb.person</code>.
     */
    public static final Person PERSON = my.jooq.entities.autogen.tables.Person.PERSON;
}
